[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "multi-channel-ad-spend-attribution-hub"
version = "1.0.0"
description = "Event-driven hybrid cloud data pipeline tracking multi-touch marketing attribution models and checkout funnel velocity."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Arjun Singh Solanki" }
]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi",
    "uvicorn",
    "boto3",
    "pandas",
    "pymysql",
    "sqlalchemy",
    "cryptography",
    "python-dotenv",
    "mlflow"
]
